### ISSUE TITLE
The bug: Connection timed out

### ISSUE THREAD

**Issue by rdyan0053** [wilmerwang/GPUSitter#3]
The bug:
```
Scramble GPU 0
[Errno 110] Connection timed out
```

![image](https://github.com/wilmerwang/GPUSnatcher/assets/53009617/1a2a4ffe-61f3-458e-8b15-84f815953e7b)

**Comment by wilmerwang** [comment]
@rdyan0053 hi,
- It appears that the email wasn't sent successfully due to a network issue. Please check if the same problem persists. 
- Perhaps the email account name you're using doesn't match the email server. I suggest testing it with a QQ email account.
- The 'pwd' in email_conf.json file is IMAP/SMTP Authorization Code, not qq password.

good luck!

**Comment by rdyan0053** [comment]
Thank you!
I usually change the file name "scramble4gpu.py" to "train.py" and run it successfully many times. I use "nohup python -u train.py &" to save the logs to the default "nohup.out". But this time it runs with an error, and then `nohup.out` has the above content `Connection timed out`. 
I guess it's because of the network problem.
Thanks again
